# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ANDemoChat' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ANDemoChat
	pod 'Firebase/Core'
	pod 'Firebase/Auth'
	pod 'Firebase/Database'
	pod 'Firebase/Storage'
	pod 'MBProgressHUD'
	pod 'MGSwipeTableCell'
	pod 'NYTPhotoViewer'
	pod 'ProgressHUD'
	pod 'IQKeyboardManagerSwift'
	pod 'JVFloatLabeledTextField'
	pod 'SDWebImage'
end
